### ISSUE TITLE
Getting Fatal error: Invalid string length

### ISSUE THREAD

**Issue by ghost** [jswk/grunt-compress-deploy#6] opened 2015-09-06 14:40 UTC
Hi there,

First of all thank you for this great task.

I am trying to use this plugin for the first time and when logging in it is currently throwing an error,

```
    Running "compress-deploy:build" (compress-deploy) task
    Verifying property compress-deploy.build exists in config...OK
    Files: prod/ -> /path/to/loction/on/the/server
    Compressing prod/ to tmp.tar.gz done
    Reading .ftppass...OK
    >> Logging in with username aUsername
    Fatal error: Invalid string length
```

Could you please let me know where I might be wrong?

following is my compress-deploy object

```
    'compress-deploy': {
        build: {
            server_sep : "/",
            clean : true,
            createDir : true,
            touch : false,
            auth: {
                host: 'somedomain.com',
                port: 21,
                authKey: 'key1'
            },
            src: 'prod',
            dest: 'path/to/loction/on/the/server'
        }
    },
```

follwoing is my .ftppass

```
    {
        "key1": {
            "username": "aUsername",
            "password": "aPassword"
        }
    }
```

Thank you,

**Comment by jswk** [comment] 2015-09-14 21:18
The configuration looks fine.
Although, I've realized that the dependencies are quite outdated. Can you try updating the ssh2 to version 0.3.6? (0.4.x introduces changes which make the upload process stall.)
Just run `npm install ssh2@0.3.6` in the project root.

**Comment by jswk** [comment] 2015-10-17 14:20
I'm closing the issue as I'm unable to reproduce it.

**Closed as completed by jswk** 2015-10-17 14:20 UTC
